# Generated by Django 4.1.5 on 2023-01-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='idea',
            new_name='building',
        ),
    ]
