# Generated by Django 4.1.5 on 2023-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_idea_room_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
