# Generated by Django 4.1.7 on 2023-03-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_building_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='accessibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
