# Generated by Django 4.1.7 on 2023-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_building_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='po',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
