# Generated by Django 4.1.7 on 2023-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_handicapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
