# Generated by Django 4.1.7 on 2023-03-09 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_accessibility_room_capacity_room_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservingPersonForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
            ],
        ),
    ]
