# Generated by Django 4.1.7 on 2023-03-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_reservingpersonform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservingPersonForm',
            new_name='ReservingPerson',
        ),
    ]
