# Generated by Django 4.1.7 on 2023-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='room',
            name='volume',
            field=models.IntegerField(default=2, max_length=32),
        ),
    ]
