# Generated by Django 4.1.7 on 2023-03-09 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_presenter_booking_presenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('wheelchair_access', 'wheelchair_access'), ('projector', 'projector'), ('whiteboard', 'whiteboard'), ('speakers', 'speakers')], max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
