# Generated by Django 4.1.7 on 2023-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_floor_room_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='volume',
            field=models.IntegerField(default=2),
        ),
    ]
