# Generated by Django 4.1.7 on 2023-03-09 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('street', models.CharField(default='', max_length=128)),
                ('town', models.CharField(max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_cennika', models.CharField(default='Cennik', max_length=255)),
                ('rzutnik_cena', models.FloatField(default=100)),
                ('tablica', models.FloatField(default=20)),
                ('audio', models.FloatField(default=250)),
                ('catering', models.FloatField(default=14.97, help_text='Za osobę')),
                ('wifi', models.FloatField(default=50)),
                ('klimatyzacja', models.FloatField(default=300)),
                ('cena_za_osobe', models.FloatField(default=20)),
                ('currency', models.CharField(choices=[('pln', 'pln'), ('usd', 'usd'), ('eur', 'eur')], default='pln', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_osob', models.PositiveIntegerField(default=10, help_text='Ile osób zmieści się w sali?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('tablica', models.BooleanField(default=False, help_text='Czy tablica do pisania ma być dostępna?')),
                ('rzutnik', models.BooleanField(default=True, help_text='Czy rzutnik jest dostępny w tej sali?')),
                ('audio', models.BooleanField(default=False, help_text='Czy system nagłośnienia ma być dostępny do wyboru w tej sali?')),
                ('catering', models.BooleanField(default=False, help_text='Czy istnieje możliwość zamówienia cateringu?')),
                ('wifi', models.BooleanField(default=False, help_text='Czy WIFI ma być dostępny przy wborze sali?')),
                ('klimatyzacja', models.BooleanField(default=False, help_text='Czy klimatyzacja jest dostępna?')),
                ('nazwa_sali', models.CharField(max_length=20, unique=True)),
                ('mozliwosc_rezerwacji_od', models.TimeField()),
                ('mozliwosc_rezerwacji_do', models.TimeField()),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.building')),
                ('cennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.cena')),
            ],
        ),
        migrations.CreateModel(
            name='Wynajem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynajem_od', models.DateTimeField()),
                ('wynajem_do', models.DateTimeField()),
                ('status_transakcji', models.BooleanField(default=False)),
                ('id_stripe', models.CharField(max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.sala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation.sala')),
            ],
        ),
        migrations.CreateModel(
            name='NumerTelefonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_telefonu', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
