# Generated by Django 4.1.7 on 2023-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='czy_dostepna_dla_osob_z_niepelnosprawnoscia',
            field=models.BooleanField(default=False),
        ),
    ]
