# Generated by Django 4.1.7 on 2023-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_sala_czy_dostepna_dla_osob_z_niepelnosprawnoscia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='pietro',
            field=models.IntegerField(default=0),
        ),
    ]
