# Generated by Django 4.1.7 on 2023-03-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_sala_pietro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumerTelefonu',
        ),
    ]
