# Generated by Django 4.1.7 on 2023-03-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_building_id_alter_room_area_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='building',
            name='town',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
